package com.bazl.dna.database.nation.converter.model.po;

import java.util.Date;

public class LabInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.INIT_SERVER_NO
     *
     * @mbggenerated
     */
    private String initServerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_TYPE
     *
     * @mbggenerated
     */
    private String labType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_REGIONALISM
     *
     * @mbggenerated
     */
    private String labRegionalism;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_NAME
     *
     * @mbggenerated
     */
    private String labName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_ENGLISH_NAME
     *
     * @mbggenerated
     */
    private String labEnglishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_SHORT_NAME
     *
     * @mbggenerated
     */
    private String labShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_ADDRESS
     *
     * @mbggenerated
     */
    private String labAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_ZIP_CODE
     *
     * @mbggenerated
     */
    private String labZipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_PHONE
     *
     * @mbggenerated
     */
    private String labPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_FAX_NO
     *
     * @mbggenerated
     */
    private String labFaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_LEVEL
     *
     * @mbggenerated
     */
    private String labLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_SUBJECTION
     *
     * @mbggenerated
     */
    private String labSubjection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.PRINCIPAL_NAME
     *
     * @mbggenerated
     */
    private String principalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.DATA_SOURCE
     *
     * @mbggenerated
     */
    private String dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_STATUS
     *
     * @mbggenerated
     */
    private String labStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.AUDITOR
     *
     * @mbggenerated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.AUDIT_IDEA
     *
     * @mbggenerated
     */
    private String auditIdea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.CREATE_DATETIME
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.UPDATE_DATETIME
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.DELETE_FLAG
     *
     * @mbggenerated
     */
    private Short deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.COVERED_AREA
     *
     * @mbggenerated
     */
    private String coveredArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LEADERS_NAME
     *
     * @mbggenerated
     */
    private String leadersName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LEADERS_PHONE
     *
     * @mbggenerated
     */
    private String leadersPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_DIRECTOR_NAME
     *
     * @mbggenerated
     */
    private String labDirectorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_DIRECTOR_PHONE
     *
     * @mbggenerated
     */
    private String labDirectorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_DBA_NAME
     *
     * @mbggenerated
     */
    private String labDbaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_INFO.LAB_DBA_PHONE
     *
     * @mbggenerated
     */
    private String labDbaPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.ID
     *
     * @return the value of LAB_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.ID
     *
     * @param id the value for LAB_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.INIT_SERVER_NO
     *
     * @return the value of LAB_INFO.INIT_SERVER_NO
     *
     * @mbggenerated
     */
    public String getInitServerNo() {
        return initServerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.INIT_SERVER_NO
     *
     * @param initServerNo the value for LAB_INFO.INIT_SERVER_NO
     *
     * @mbggenerated
     */
    public void setInitServerNo(String initServerNo) {
        this.initServerNo = initServerNo == null ? null : initServerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_TYPE
     *
     * @return the value of LAB_INFO.LAB_TYPE
     *
     * @mbggenerated
     */
    public String getLabType() {
        return labType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_TYPE
     *
     * @param labType the value for LAB_INFO.LAB_TYPE
     *
     * @mbggenerated
     */
    public void setLabType(String labType) {
        this.labType = labType == null ? null : labType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_REGIONALISM
     *
     * @return the value of LAB_INFO.LAB_REGIONALISM
     *
     * @mbggenerated
     */
    public String getLabRegionalism() {
        return labRegionalism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_REGIONALISM
     *
     * @param labRegionalism the value for LAB_INFO.LAB_REGIONALISM
     *
     * @mbggenerated
     */
    public void setLabRegionalism(String labRegionalism) {
        this.labRegionalism = labRegionalism == null ? null : labRegionalism.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_NAME
     *
     * @return the value of LAB_INFO.LAB_NAME
     *
     * @mbggenerated
     */
    public String getLabName() {
        return labName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_NAME
     *
     * @param labName the value for LAB_INFO.LAB_NAME
     *
     * @mbggenerated
     */
    public void setLabName(String labName) {
        this.labName = labName == null ? null : labName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_ENGLISH_NAME
     *
     * @return the value of LAB_INFO.LAB_ENGLISH_NAME
     *
     * @mbggenerated
     */
    public String getLabEnglishName() {
        return labEnglishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_ENGLISH_NAME
     *
     * @param labEnglishName the value for LAB_INFO.LAB_ENGLISH_NAME
     *
     * @mbggenerated
     */
    public void setLabEnglishName(String labEnglishName) {
        this.labEnglishName = labEnglishName == null ? null : labEnglishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_SHORT_NAME
     *
     * @return the value of LAB_INFO.LAB_SHORT_NAME
     *
     * @mbggenerated
     */
    public String getLabShortName() {
        return labShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_SHORT_NAME
     *
     * @param labShortName the value for LAB_INFO.LAB_SHORT_NAME
     *
     * @mbggenerated
     */
    public void setLabShortName(String labShortName) {
        this.labShortName = labShortName == null ? null : labShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_ADDRESS
     *
     * @return the value of LAB_INFO.LAB_ADDRESS
     *
     * @mbggenerated
     */
    public String getLabAddress() {
        return labAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_ADDRESS
     *
     * @param labAddress the value for LAB_INFO.LAB_ADDRESS
     *
     * @mbggenerated
     */
    public void setLabAddress(String labAddress) {
        this.labAddress = labAddress == null ? null : labAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_ZIP_CODE
     *
     * @return the value of LAB_INFO.LAB_ZIP_CODE
     *
     * @mbggenerated
     */
    public String getLabZipCode() {
        return labZipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_ZIP_CODE
     *
     * @param labZipCode the value for LAB_INFO.LAB_ZIP_CODE
     *
     * @mbggenerated
     */
    public void setLabZipCode(String labZipCode) {
        this.labZipCode = labZipCode == null ? null : labZipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_PHONE
     *
     * @return the value of LAB_INFO.LAB_PHONE
     *
     * @mbggenerated
     */
    public String getLabPhone() {
        return labPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_PHONE
     *
     * @param labPhone the value for LAB_INFO.LAB_PHONE
     *
     * @mbggenerated
     */
    public void setLabPhone(String labPhone) {
        this.labPhone = labPhone == null ? null : labPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_FAX_NO
     *
     * @return the value of LAB_INFO.LAB_FAX_NO
     *
     * @mbggenerated
     */
    public String getLabFaxNo() {
        return labFaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_FAX_NO
     *
     * @param labFaxNo the value for LAB_INFO.LAB_FAX_NO
     *
     * @mbggenerated
     */
    public void setLabFaxNo(String labFaxNo) {
        this.labFaxNo = labFaxNo == null ? null : labFaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.EMAIL
     *
     * @return the value of LAB_INFO.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.EMAIL
     *
     * @param email the value for LAB_INFO.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_LEVEL
     *
     * @return the value of LAB_INFO.LAB_LEVEL
     *
     * @mbggenerated
     */
    public String getLabLevel() {
        return labLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_LEVEL
     *
     * @param labLevel the value for LAB_INFO.LAB_LEVEL
     *
     * @mbggenerated
     */
    public void setLabLevel(String labLevel) {
        this.labLevel = labLevel == null ? null : labLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_SUBJECTION
     *
     * @return the value of LAB_INFO.LAB_SUBJECTION
     *
     * @mbggenerated
     */
    public String getLabSubjection() {
        return labSubjection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_SUBJECTION
     *
     * @param labSubjection the value for LAB_INFO.LAB_SUBJECTION
     *
     * @mbggenerated
     */
    public void setLabSubjection(String labSubjection) {
        this.labSubjection = labSubjection == null ? null : labSubjection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.PRINCIPAL_NAME
     *
     * @return the value of LAB_INFO.PRINCIPAL_NAME
     *
     * @mbggenerated
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.PRINCIPAL_NAME
     *
     * @param principalName the value for LAB_INFO.PRINCIPAL_NAME
     *
     * @mbggenerated
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName == null ? null : principalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.REMARK
     *
     * @return the value of LAB_INFO.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.REMARK
     *
     * @param remark the value for LAB_INFO.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.DATA_SOURCE
     *
     * @return the value of LAB_INFO.DATA_SOURCE
     *
     * @mbggenerated
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.DATA_SOURCE
     *
     * @param dataSource the value for LAB_INFO.DATA_SOURCE
     *
     * @mbggenerated
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_STATUS
     *
     * @return the value of LAB_INFO.LAB_STATUS
     *
     * @mbggenerated
     */
    public String getLabStatus() {
        return labStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_STATUS
     *
     * @param labStatus the value for LAB_INFO.LAB_STATUS
     *
     * @mbggenerated
     */
    public void setLabStatus(String labStatus) {
        this.labStatus = labStatus == null ? null : labStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.AUDITOR
     *
     * @return the value of LAB_INFO.AUDITOR
     *
     * @mbggenerated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.AUDITOR
     *
     * @param auditor the value for LAB_INFO.AUDITOR
     *
     * @mbggenerated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.AUDIT_IDEA
     *
     * @return the value of LAB_INFO.AUDIT_IDEA
     *
     * @mbggenerated
     */
    public String getAuditIdea() {
        return auditIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.AUDIT_IDEA
     *
     * @param auditIdea the value for LAB_INFO.AUDIT_IDEA
     *
     * @mbggenerated
     */
    public void setAuditIdea(String auditIdea) {
        this.auditIdea = auditIdea == null ? null : auditIdea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.CREATE_USER
     *
     * @return the value of LAB_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.CREATE_USER
     *
     * @param createUser the value for LAB_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.CREATE_DATETIME
     *
     * @return the value of LAB_INFO.CREATE_DATETIME
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.CREATE_DATETIME
     *
     * @param createDatetime the value for LAB_INFO.CREATE_DATETIME
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.UPDATE_USER
     *
     * @return the value of LAB_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.UPDATE_USER
     *
     * @param updateUser the value for LAB_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.UPDATE_DATETIME
     *
     * @return the value of LAB_INFO.UPDATE_DATETIME
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.UPDATE_DATETIME
     *
     * @param updateDatetime the value for LAB_INFO.UPDATE_DATETIME
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.DELETE_FLAG
     *
     * @return the value of LAB_INFO.DELETE_FLAG
     *
     * @mbggenerated
     */
    public Short getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.DELETE_FLAG
     *
     * @param deleteFlag the value for LAB_INFO.DELETE_FLAG
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Short deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.COVERED_AREA
     *
     * @return the value of LAB_INFO.COVERED_AREA
     *
     * @mbggenerated
     */
    public String getCoveredArea() {
        return coveredArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.COVERED_AREA
     *
     * @param coveredArea the value for LAB_INFO.COVERED_AREA
     *
     * @mbggenerated
     */
    public void setCoveredArea(String coveredArea) {
        this.coveredArea = coveredArea == null ? null : coveredArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LEADERS_NAME
     *
     * @return the value of LAB_INFO.LEADERS_NAME
     *
     * @mbggenerated
     */
    public String getLeadersName() {
        return leadersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LEADERS_NAME
     *
     * @param leadersName the value for LAB_INFO.LEADERS_NAME
     *
     * @mbggenerated
     */
    public void setLeadersName(String leadersName) {
        this.leadersName = leadersName == null ? null : leadersName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LEADERS_PHONE
     *
     * @return the value of LAB_INFO.LEADERS_PHONE
     *
     * @mbggenerated
     */
    public String getLeadersPhone() {
        return leadersPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LEADERS_PHONE
     *
     * @param leadersPhone the value for LAB_INFO.LEADERS_PHONE
     *
     * @mbggenerated
     */
    public void setLeadersPhone(String leadersPhone) {
        this.leadersPhone = leadersPhone == null ? null : leadersPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_DIRECTOR_NAME
     *
     * @return the value of LAB_INFO.LAB_DIRECTOR_NAME
     *
     * @mbggenerated
     */
    public String getLabDirectorName() {
        return labDirectorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_DIRECTOR_NAME
     *
     * @param labDirectorName the value for LAB_INFO.LAB_DIRECTOR_NAME
     *
     * @mbggenerated
     */
    public void setLabDirectorName(String labDirectorName) {
        this.labDirectorName = labDirectorName == null ? null : labDirectorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_DIRECTOR_PHONE
     *
     * @return the value of LAB_INFO.LAB_DIRECTOR_PHONE
     *
     * @mbggenerated
     */
    public String getLabDirectorPhone() {
        return labDirectorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_DIRECTOR_PHONE
     *
     * @param labDirectorPhone the value for LAB_INFO.LAB_DIRECTOR_PHONE
     *
     * @mbggenerated
     */
    public void setLabDirectorPhone(String labDirectorPhone) {
        this.labDirectorPhone = labDirectorPhone == null ? null : labDirectorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_DBA_NAME
     *
     * @return the value of LAB_INFO.LAB_DBA_NAME
     *
     * @mbggenerated
     */
    public String getLabDbaName() {
        return labDbaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_DBA_NAME
     *
     * @param labDbaName the value for LAB_INFO.LAB_DBA_NAME
     *
     * @mbggenerated
     */
    public void setLabDbaName(String labDbaName) {
        this.labDbaName = labDbaName == null ? null : labDbaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_INFO.LAB_DBA_PHONE
     *
     * @return the value of LAB_INFO.LAB_DBA_PHONE
     *
     * @mbggenerated
     */
    public String getLabDbaPhone() {
        return labDbaPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_INFO.LAB_DBA_PHONE
     *
     * @param labDbaPhone the value for LAB_INFO.LAB_DBA_PHONE
     *
     * @mbggenerated
     */
    public void setLabDbaPhone(String labDbaPhone) {
        this.labDbaPhone = labDbaPhone == null ? null : labDbaPhone.trim();
    }
}