package com.bazl.dna.lims.core.webservice.caseSampleLib;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-10-09T09:04:38.276+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", name = "caseSampleLibPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CaseSampleLibPortType {

    @WebMethod
    @RequestWrapper(localName = "getCaseSampleListFromLibByCaseID", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetCaseSampleListFromLibByCaseID")
    @ResponseWrapper(localName = "getCaseSampleListFromLibByCaseIDResponse", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetCaseSampleListFromLibByCaseIDResponse")
    @WebResult(name = "out", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
    public CaseSampleLib getCaseSampleListFromLibByCaseID(
            @WebParam(name = "in0", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
            String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getStoreSampleCntByCaseID", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetStoreSampleCntByCaseID")
    @ResponseWrapper(localName = "getStoreSampleCntByCaseIDResponse", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetStoreSampleCntByCaseIDResponse")
    @WebResult(name = "out", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
    public int getStoreSampleCntByCaseID(
            @WebParam(name = "in0", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
            String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getStoredSampleCnt", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetStoredSampleCnt")
    @ResponseWrapper(localName = "getStoredSampleCntResponse", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetStoredSampleCntResponse")
    @WebResult(name = "out", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
    public ArrayOfCaseSampleLib getStoredSampleCnt(
            @WebParam(name = "in0", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
            String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getSamples", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetSamples")
    @ResponseWrapper(localName = "getSamplesResponse", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.GetSamplesResponse")
    @WebResult(name = "out", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
    public ArrayOfSampleNoDomain getSamples(
            @WebParam(name = "in0", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
            String in0
    );

    @WebMethod
    @RequestWrapper(localName = "updateSampleState", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.UpdateSampleState")
    @ResponseWrapper(localName = "updateSampleStateResponse", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.caseSampleLib.UpdateSampleStateResponse")
    public void updateSampleState(
            @WebParam(name = "in0", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
            ArrayOfString in0,
            @WebParam(name = "in1", targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com")
            int in1
    );
}
