package com.bazl.dna.lims.core.webservice.caseSampleLib;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-10-09T09:04:38.309+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "caseSampleLib", 
                  wsdlLocation = "http://127.0.0.1:8080/DnaWebservice/services/caseSampleLib?wsdl",
                  targetNamespace = "http://casesamplelib.webservice.web.dna.todaysoft.com") 
public class CaseSampleLib_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://casesamplelib.webservice.web.dna.todaysoft.com", "caseSampleLib");
    public final static QName CaseSampleLibHttpPort = new QName("http://casesamplelib.webservice.web.dna.todaysoft.com", "caseSampleLibHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/DnaWebservice/services/caseSampleLib?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CaseSampleLib_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/DnaWebservice/services/caseSampleLib?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CaseSampleLib_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaseSampleLib_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaseSampleLib_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CaseSampleLib_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CaseSampleLib_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CaseSampleLib_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CaseSampleLibPortType
     */
    @WebEndpoint(name = "caseSampleLibHttpPort")
    public CaseSampleLibPortType getCaseSampleLibHttpPort() {
        return super.getPort(CaseSampleLibHttpPort, CaseSampleLibPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaseSampleLibPortType
     */
    @WebEndpoint(name = "caseSampleLibHttpPort")
    public CaseSampleLibPortType getCaseSampleLibHttpPort(WebServiceFeature... features) {
        return super.getPort(CaseSampleLibHttpPort, CaseSampleLibPortType.class, features);
    }

}
