package com.bazl.dna.lims.core.webservice.basicInfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-10-09T09:08:33.857+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "basicInfo", 
                  wsdlLocation = "http://127.0.0.1:8080/DnaWebservice/services/basicInfo?wsdl",
                  targetNamespace = "http://BasicInfo.webservice.web.dna.todaysoft.com") 
public class BasicInfo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://BasicInfo.webservice.web.dna.todaysoft.com", "basicInfo");
    public final static QName BasicInfoHttpPort = new QName("http://BasicInfo.webservice.web.dna.todaysoft.com", "basicInfoHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/DnaWebservice/services/basicInfo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BasicInfo.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/DnaWebservice/services/basicInfo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BasicInfo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BasicInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicInfo() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BasicInfo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BasicInfo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BasicInfo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BasicInfoPortType
     */
    @WebEndpoint(name = "basicInfoHttpPort")
    public BasicInfoPortType getBasicInfoHttpPort() {
        return super.getPort(BasicInfoHttpPort, BasicInfoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicInfoPortType
     */
    @WebEndpoint(name = "basicInfoHttpPort")
    public BasicInfoPortType getBasicInfoHttpPort(WebServiceFeature... features) {
        return super.getPort(BasicInfoHttpPort, BasicInfoPortType.class, features);
    }

}
