## Access Token
ACCESS_TOKEN_SECRET: test
ACCESS_TOKEN_EXPIRY_MIN: 14400


## datasource
spring:
  
  cloud:
    stream:
      default:
        ##使用自定义组配置可以保证断网重连机制
        group: springCloudBus-${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              queue-declaration-retries: 2000
              recovery-interval: 5000
              queue-name-group-only: true

## zipkin
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    enabled: true
    web: 
      client: 
        enabled: true
    sampler:
      probability: 1.0

## rabbitmq
  rabbitmq:
    host: 47.92.219.7
    port: 5672
    username: admin
    password: admin123
    connection-timeout: 100000

## redis
  redis:
    enable: true
    host: 47.92.219.7
    port: 6379
    password: pw
    timeout: 10000000
    jedis:
      pool:
        max-active: 1024
        max-wait: 20000
        max-idle: 200
        min-idle: 10

## feign 
feign:
  hystrix:
    enabled: true
            
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000
            
## ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

management: 
  endpoints:
    web:
      exposure:
        include: "*"
