spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.100.79.169:3316/dnacloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      
  redis:
    database: 1
  
  data:
    redis:
      repositories:
        enabled: false
          
