spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.130:1521:orcl
#    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: dpznsy
    password: dpznsy
    initialSize: 30
    minIdle: 30
    maxActive: 500
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    
#以下为文件上传配置路径
proxyImg: D:/ftpimg/proxy_img/

japt: http://192.168.1.130:8081

#以下为上传ftp所需配置
ftpIp: 192.168.1.129
ftpPort: 21
ftpPersonImg: person_img
ftpSampleImg: sample_img
ftpProxyImg: proxy_img
ftpFilePath: file
ftpUser: test
ftpPassword: test
ftpTomcat: 9091

bendiFilePath: D:/download2/