spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.100.79.169:3316/dnamix?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    
      initial-size: 30
      min-idle: 50
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select * from `dict_item` limit 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
    dna:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.100.79.169:3316/dnacloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0

#以下为上传ftp所需配置
ftpIp: 192.168.1.222
ftpPort: 21
ftpUser: test
ftpPassword: test
ftpTomcat: 9091
ftpchromePath: chrome/ChromeSetup.exe

filePath: D:/uploadPdf/
bendiFilePath: D:/download2/ChromeSetup.exe
