package com.bazl.dna.lims.core.webservice.client.libMatch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-09-10T16:38:46.973+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", name = "libMatchPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface LibMatchPortType {

    @WebMethod
    @RequestWrapper(localName = "getLibMatchResult", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchResult")
    @ResponseWrapper(localName = "getLibMatchResultResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchResultResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.WSTotalRelativeMatchResult getLibMatchResult(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in0
    );

    @WebMethod
    @RequestWrapper(localName = "parentageMatchTwoForOne", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.ParentageMatchTwoForOne")
    @ResponseWrapper(localName = "parentageMatchTwoForOneResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.ParentageMatchTwoForOneResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.ArrayOfWSLibMatchResult parentageMatchTwoForOne(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSLibMatchSourceSetting in2
    );

    @WebMethod
    @RequestWrapper(localName = "getLibMathcResultGroup", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMathcResultGroup")
    @ResponseWrapper(localName = "getLibMathcResultGroupResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMathcResultGroupResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.ArrayOfWSLibMatchGroupResult getLibMathcResultGroup(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSSearchLibMatchRecordOption in0
    );

    @WebMethod
    @RequestWrapper(localName = "parentageSubmitAndMatch", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.ParentageSubmitAndMatch")
    @ResponseWrapper(localName = "parentageSubmitAndMatchResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.ParentageSubmitAndMatchResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.WSParentageSubmitAndMatchResult parentageSubmitAndMatch(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in3,
            @WebParam(name = "in4", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in4
    );

    @WebMethod
    @RequestWrapper(localName = "lookForUnknownContributor", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.LookForUnknownContributor")
    @ResponseWrapper(localName = "lookForUnknownContributorResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.LookForUnknownContributorResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.ArrayOfWSGenotype lookForUnknownContributor(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSCombinedGenotype in0
    );

    @WebMethod
    @RequestWrapper(localName = "verifyGroupState", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.VerifyGroupState")
    @ResponseWrapper(localName = "verifyGroupStateResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.VerifyGroupStateResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int verifyGroupState(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2
    );

    @WebMethod
    @RequestWrapper(localName = "singleParentageSubmit", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.SingleParentageSubmit")
    @ResponseWrapper(localName = "singleParentageSubmitResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.SingleParentageSubmitResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.WSParentageSubmitAndMatchResult singleParentageSubmit(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in3
    );

    @WebMethod
    @RequestWrapper(localName = "getLibMatchRecordList", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordList")
    @ResponseWrapper(localName = "getLibMatchRecordListResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordListResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.WSLibMatchResultAndTotalCount getLibMatchRecordList(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSSearchLibMatchRecordOption in0
    );

    @WebMethod
    @RequestWrapper(localName = "checkCompareWithZKperson", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.CheckCompareWithZKperson")
    @ResponseWrapper(localName = "checkCompareWithZKpersonResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.CheckCompareWithZKpersonResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.WSSubmitAndMatchResult checkCompareWithZKperson(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2
    );

    @WebMethod
    @RequestWrapper(localName = "updLibMatchRecordByBarcode", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.UpdLibMatchRecordByBarcode")
    @ResponseWrapper(localName = "updLibMatchRecordByBarcodeResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.UpdLibMatchRecordByBarcodeResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int updLibMatchRecordByBarcode(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in4
    );

    @WebMethod
    @RequestWrapper(localName = "getLibMatchRecordNotCheckedGroupCnt", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordNotCheckedGroupCnt")
    @ResponseWrapper(localName = "getLibMatchRecordNotCheckedGroupCntResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordNotCheckedGroupCntResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int getLibMatchRecordNotCheckedGroupCnt(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSSearchLibMatchRecordOption in0
    );

    @WebMethod
    @RequestWrapper(localName = "submitAndMatch", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.SubmitAndMatch")
    @ResponseWrapper(localName = "submitAndMatchResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.SubmitAndMatchResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.WSSubmitAndMatchResult submitAndMatch(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2
    );

    @WebMethod
    @RequestWrapper(localName = "getLibMatchRecordNotCheckedCnt", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordNotCheckedCnt")
    @ResponseWrapper(localName = "getLibMatchRecordNotCheckedCntResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordNotCheckedCntResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int getLibMatchRecordNotCheckedCnt(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSSearchLibMatchRecordOption in0
    );

    @WebMethod
    @RequestWrapper(localName = "libMatch", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.LibMatch")
    @ResponseWrapper(localName = "libMatchResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.LibMatchResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.ArrayOfWSLibMatchResult libMatch(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSLibMatchSourceSetting in1
    );

    @WebMethod
    @RequestWrapper(localName = "getLibMathcResultGroupIdList", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMathcResultGroupIdList")
    @ResponseWrapper(localName = "getLibMathcResultGroupIdListResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMathcResultGroupIdListResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public ArrayOfString getLibMathcResultGroupIdList(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSSearchLibMatchRecordOption in0
    );

    @WebMethod
    @RequestWrapper(localName = "verifyRecordState", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.VerifyRecordState")
    @ResponseWrapper(localName = "verifyRecordStateResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.VerifyRecordStateResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int verifyRecordState(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2
    );

    @WebMethod
    @RequestWrapper(localName = "getLibMatchRecordListByGroupID", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordListByGroupID")
    @ResponseWrapper(localName = "getLibMatchRecordListByGroupIDResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.libMatch.GetLibMatchRecordListByGroupIDResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public com.bazl.dna.lims.core.webservice.client.libMatch.ArrayOfWSLibMatchGroupRecord getLibMatchRecordListByGroupID(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            com.bazl.dna.lims.core.webservice.client.libMatch.WSSearchLibMatchRecordOption in0
    );
}
