package com.bazl.dna.lims.core.webservice.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-09-23T10:35:56.801+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "QueryDataService", 
                  wsdlLocation = "http://127.0.0.1:8088/LimsDataService/QueryDataService?wsdl",
                  targetNamespace = "http://services.webservice.lims.dna.com") 
public class QueryDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.webservice.lims.dna.com", "QueryDataService");
    public final static QName QueryDataServiceHttpPort = new QName("http://services.webservice.lims.dna.com", "QueryDataServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8088/LimsDataService/QueryDataService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryDataService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8088/LimsDataService/QueryDataService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryDataService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryDataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryDataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryDataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns QueryDataServicePortType
     */
    @WebEndpoint(name = "QueryDataServiceHttpPort")
    public QueryDataServicePortType getQueryDataServiceHttpPort() {
        return super.getPort(QueryDataServiceHttpPort, QueryDataServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryDataServicePortType
     */
    @WebEndpoint(name = "QueryDataServiceHttpPort")
    public QueryDataServicePortType getQueryDataServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(QueryDataServiceHttpPort, QueryDataServicePortType.class, features);
    }

}
