#部署目录
deploy:
  name: /Users/zhaoyong/Downloads/deploy
  version: 1.0.0-SNAPSHOT
  suffix: jar
  project: bazl-dna-system

#服务器配置  
servers:
  deploy: true
  name: /usr/local/tomcat/dnacloud
  ip: 192.168.1.199
  port: 22
  username: root
  password: root