package com.bazl.dna.lims.core.webservice.client.submitInfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-09-10T16:37:31.357+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", name = "submitInfoPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SubmitInfoPortType {

    @WebMethod
    @RequestWrapper(localName = "submitRelativeGenotype", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitRelativeGenotype")
    @ResponseWrapper(localName = "submitRelativeGenotypeResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitRelativeGenotypeResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int submitRelativeGenotype(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            WSGenotypeGeneral in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2,
            @WebParam(name = "in3", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in3,
            @WebParam(name = "in4", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in4
    );

    @WebMethod
    @RequestWrapper(localName = "submitCase", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitCase")
    @ResponseWrapper(localName = "submitCaseResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitCaseResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int submitCase(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            WSCase in0
    );

    @WebMethod
    @RequestWrapper(localName = "submitPersonInfo", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitPersonInfo")
    @ResponseWrapper(localName = "submitPersonInfoResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitPersonInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int submitPersonInfo(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            WSPerson in0
    );

    @WebMethod
    @RequestWrapper(localName = "submitGenotype", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitGenotype")
    @ResponseWrapper(localName = "submitGenotypeResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitGenotypeResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int submitGenotype(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            WSGenotypeGeneral in0,
            @WebParam(name = "in1", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in1,
            @WebParam(name = "in2", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            int in2
    );

    @WebMethod
    @RequestWrapper(localName = "submitSampleInfo", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitSampleInfo")
    @ResponseWrapper(localName = "submitSampleInfoResponse", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com", className = "com.bazl.dna.lims.core.webservice.client.submitInfo.SubmitSampleInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
    public int submitSampleInfo(
            @WebParam(name = "in0", targetNamespace = "http://submitMatchDefaultSetting.webservice.web.dna.todaysoft.com")
            WSSampleInfo in0
    );
}
