server:
  port: 8717
    
spring:
  application:
    name: bazl-dna-database-lims-converter
    
    
task:
  maxPoolSize: 60
  corePoolSize: 40
  queueCapacity: 100
  keepAliveSeconds: 90
  threadNamePrefix: LimsGeneDataTask-